esk_defconfig: Disable per-task stackprotector This is automatically enabled on newer compilers, however it kills off the __stack_chk_guard symbol which is required by modules.
ERROR: Differences between ksymtab and symbol list detected!
Symbols missing from ksymtab:
 - __stack_chk_guard

Signed-off-by: bachnxuan <bachnxuan@gmail.com>